name: Bug Report
description: Report a bug or unexpected behavior
title: "🐛 [Bug]: "
labels: ["bug", "triage"]
assignees:
  - BayBreezy

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us resolve it quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import '...'
        2. Call function '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, this happened...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: typescript
      placeholder: |
        import { getMaterialFileIcon } from '@baybreezy/file-extension-icon';

        const icon = getMaterialFileIcon('test.js');
        console.log(icon); // Error occurs here
    validations:
      required: false

  - type: dropdown
    id: api
    attributes:
      label: Which API are you using?
      options:
        - getMaterialFileIcon
        - getMaterialFolderIcon
        - getVSIFileIcon
        - getVSIFolderIcon
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of @baybreezy/file-extension-icon are you using?
      placeholder: e.g., 0.0.1
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: e.g., 20.10.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Node.js
        - Browser
        - Edge Runtime (Vercel, Cloudflare Workers, etc.)
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.)
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for existing issues before creating this one
          required: true
        - label: I have included all relevant information above
          required: true
        - label: I am using the latest version of the package
          required: false
